name: Build .gex

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download gm82gex
      run: wget https://raw.githubusercontent.com/GM82Project/gm82gex/main/gm82gex.py
    - name: Build gm82test.gex
      run: python gm82gex.py ${{github.workspace}}/gm82test.gej --noinstall
    - name: Build gm82test_stub.gex
      run: python gm82gex.py ${{github.workspace}}/gm82test_stub.gej --noinstall
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: gm82test
        path: gm82test*.gex
